# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb55512fc2ce4521274592d62a91ed327cd343c79265e831f310f92a9929a5125b55c20ee4c64bc01b195c9a6e407e844fb3e251f470254353518f023e9f99a2

test:
  secret_key_base: ba819cc1f54aec5b681a0913f8b68f6ce10d1a41d1a9b2af1ef1eaab89d2c76009f47d704f12694d53e866ae52c82bcfe14f01dcf31b15e52350590a63ae5840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
